pipeline:
  identifier: Build_Manjunath28_harness_demo_1780865310852
  name: Build harness-demo
  orgIdentifier: default
  projectIdentifier: Harnessdemo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Manjunath28/harness-demo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Run
                  identifier: Run
                  spec:
                    shell: Sh
                    command: |-
                      cd app
                      npm ci
                  description: install dependency
              - step:
                  type: Run
                  name: Run_Tests
                  identifier: Run_Tests
                  spec:
                    shell: Sh
                    command: |-
                      cd app
                      npm test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Manjunathpersonal
                    repo: pes2ug19cs219/harness-test
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: app/Dockerfile
                    context: app
              - step:
                  type: Run
                  name: sec-scan
                  identifier: secscan
                  spec:
                    shell: Sh
                    command: |-
                      # Install Trivy
                      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

                      # Security Gate: FAIL on CRITICAL vulnerabilities
                      echo "=== Container Security Scan ==="
                      trivy image --exit-code 1 --severity CRITICAL --no-progress pes2ug19cs219/harness-test:<+pipeline.sequenceId>
                  description: Trivy scan to find the vul in the container images
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - stage:
        name: deploy-k8s
        identifier: deployk8s
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: harnessapp
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: rancherdesktop
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 2m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
